DO
$body$
BEGIN
   IF NOT EXISTS (
      SELECT *
      FROM   pg_catalog.pg_user
      WHERE  usename = 'mobileapp') THEN

      CREATE ROLE mobileapp LOGIN PASSWORD 'agh';
   END IF;
END
$body$
;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO mobileapp;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public to mobileapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES  TO mobileapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE ON SEQUENCES TO mobileapp;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON ALL TABLES TO mobileapp;
